name: 更新状态徽章

on:
  workflow_run:
    workflows: ["Rust CI/CD"]
    types:
      - completed

jobs:
  update-badges:
    name: 更新README徽章
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 设置Git用户
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: 获取最新版本
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "最新版本: ${VERSION}"

      - name: 更新README徽章
        run: |
          # 获取仓库信息
          REPO="${GITHUB_REPOSITORY}"
          BRANCH="main"

          # 创建徽章链接
          BUILD_BADGE="[![构建状态](https://github.com/${REPO}/actions/workflows/rust.yml/badge.svg?branch=${BRANCH})](https://github.com/${REPO}/actions/workflows/rust.yml)"
          VERSION_BADGE="[![版本](https://img.shields.io/badge/版本-${{ steps.get_version.outputs.version }}-blue)](https://github.com/${REPO}/releases/latest)"
          CRATES_BADGE="[![Crates.io](https://img.shields.io/crates/v/mcp-sqlite)](https://crates.io/crates/mcp-sqlite)"
          DOCS_BADGE="[![文档](https://docs.rs/mcp-sqlite/badge.svg)](https://docs.rs/mcp-sqlite)"
          LICENSE_BADGE="[![许可证](https://img.shields.io/badge/许可证-MIT-green)](https://github.com/${REPO}/blob/main/LICENSE)"

          # 更新README.md
          sed -i "1s/^# SQLite MCP服务器/# SQLite MCP服务器\n\n${BUILD_BADGE} ${VERSION_BADGE} ${CRATES_BADGE} ${DOCS_BADGE} ${LICENSE_BADGE}/" README.md

          # 检查是否有更改
          if git diff --quiet README.md; then
            echo "README.md没有更改，无需提交"
            exit 0
          fi

          # 提交更改
          git add README.md
          git commit -m "更新README徽章 [skip ci]"
          git push
