name: 文档部署

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: 构建文档
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 安装Rust工具链
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: 缓存Rust依赖
        uses: Swatinem/rust-cache@v2

      - name: 生成文档
        run: |
          cargo doc --no-deps --document-private-items
          echo "<meta http-equiv=\"refresh\" content=\"0; url=mcp_sqlite\">" > target/doc/index.html

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 上传文档
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy:
    name: 部署文档
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
